source 'https://rubygems.org'
gem 'rails', '4.2.5.1'
gem 'sqlite3'
gem 'sass-rails'   #, '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
	gem 'awesome_print'
  gem 'bullet'
  gem 'byebug'
  gem 'capistrano', '~> 3.4'
  gem 'capistrano3-delayed-job', '~> 1.0'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano-passenger'
  gem 'dotenv-rails'
  gem 'letter_opener'
  gem 'rspec-rails', '~> 3.0'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end

group :production do 
  #gem 'capistrano-hipchat'
  gem 'daemons'
  gem 'delayed_job_active_record'
  gem 'delayed_job_web'
end

#gem 'administrate', '~> 0.1.3'
gem 'administrate', github: 'thoughtbot/administrate'
gem 'sprockets-rails', '~> 2.3.3'
gem 'devise'
gem 'cancancan'
gem 'chartkick'
gem 'exception_notification'
gem 'faraday'
gem 'faraday_middleware'
gem 'friendly_id'
gem 'hipchat'
gem 'jquery-turbolinks'
gem 'mail_form'
gem 'mysql2'
gem 'nokogiri', '1.6.6.2'
gem 'redcarpet'
gem 'semantic-ui-sass', github: 'doabit/semantic-ui-sass'
gem 'simple_form'
gem 'stripe'
gem 'twilio-ruby'

