require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CitationSourcesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CitationSource. As you add validations to CitationSource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CitationSourcesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all citation_sources as @citation_sources" do
      citation_source = CitationSource.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:citation_sources)).to eq([citation_source])
    end
  end

  describe "GET #show" do
    it "assigns the requested citation_source as @citation_source" do
      citation_source = CitationSource.create! valid_attributes
      get :show, {:id => citation_source.to_param}, valid_session
      expect(assigns(:citation_source)).to eq(citation_source)
    end
  end

  describe "GET #new" do
    it "assigns a new citation_source as @citation_source" do
      get :new, {}, valid_session
      expect(assigns(:citation_source)).to be_a_new(CitationSource)
    end
  end

  describe "GET #edit" do
    it "assigns the requested citation_source as @citation_source" do
      citation_source = CitationSource.create! valid_attributes
      get :edit, {:id => citation_source.to_param}, valid_session
      expect(assigns(:citation_source)).to eq(citation_source)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CitationSource" do
        expect {
          post :create, {:citation_source => valid_attributes}, valid_session
        }.to change(CitationSource, :count).by(1)
      end

      it "assigns a newly created citation_source as @citation_source" do
        post :create, {:citation_source => valid_attributes}, valid_session
        expect(assigns(:citation_source)).to be_a(CitationSource)
        expect(assigns(:citation_source)).to be_persisted
      end

      it "redirects to the created citation_source" do
        post :create, {:citation_source => valid_attributes}, valid_session
        expect(response).to redirect_to(CitationSource.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved citation_source as @citation_source" do
        post :create, {:citation_source => invalid_attributes}, valid_session
        expect(assigns(:citation_source)).to be_a_new(CitationSource)
      end

      it "re-renders the 'new' template" do
        post :create, {:citation_source => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested citation_source" do
        citation_source = CitationSource.create! valid_attributes
        put :update, {:id => citation_source.to_param, :citation_source => new_attributes}, valid_session
        citation_source.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested citation_source as @citation_source" do
        citation_source = CitationSource.create! valid_attributes
        put :update, {:id => citation_source.to_param, :citation_source => valid_attributes}, valid_session
        expect(assigns(:citation_source)).to eq(citation_source)
      end

      it "redirects to the citation_source" do
        citation_source = CitationSource.create! valid_attributes
        put :update, {:id => citation_source.to_param, :citation_source => valid_attributes}, valid_session
        expect(response).to redirect_to(citation_source)
      end
    end

    context "with invalid params" do
      it "assigns the citation_source as @citation_source" do
        citation_source = CitationSource.create! valid_attributes
        put :update, {:id => citation_source.to_param, :citation_source => invalid_attributes}, valid_session
        expect(assigns(:citation_source)).to eq(citation_source)
      end

      it "re-renders the 'edit' template" do
        citation_source = CitationSource.create! valid_attributes
        put :update, {:id => citation_source.to_param, :citation_source => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested citation_source" do
      citation_source = CitationSource.create! valid_attributes
      expect {
        delete :destroy, {:id => citation_source.to_param}, valid_session
      }.to change(CitationSource, :count).by(-1)
    end

    it "redirects to the citation_sources list" do
      citation_source = CitationSource.create! valid_attributes
      delete :destroy, {:id => citation_source.to_param}, valid_session
      expect(response).to redirect_to(citation_sources_url)
    end
  end

end
